# printers.properties
# Formato: nombre_impresora.ip=DIRECCION_IP
#          nombre_impresora.port=PUERTO (usualmente 9100 para ESC/POS RAW)

principal.ip=192.168.1.105
principal.port=9100
principal.copias=0
principal.tipoConexion=red
#principal.papelSize=48
principal.logo=logo.jpg

POS-80.ip=192.168.1.105
POS-80.port=9100
POS-80.copias=0
POS-80.tipoConexion=usb
#POS-80.papelSize=48
#POS-80.logo=logo.jpg