; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=TestInstaller
AppVersion=0.5
DefaultDirName={pf}\TestInstaller
DefaultGroupName=CDsoft
OutputBaseFilename=TestInstallerSetup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[CustomMessages]
spanish.WelcomeLabel1=¡Bienvenido al instalador de TestInstaller un servicio de seridor de impresion.!
spanish.ExitSetupMessage=¿Está seguro de que desea cancelar la instalación de TestInstaller?


[Files]
; mi app .exe
;Source: "E:\cesar\Documents\servidor_impresion\PrintServer.exe"; DestDir: "{app}"; Flags: ignoreversion
; Amazon Corretto
; Source: "E:\cesar\Documents\servidor_impresion\amazon-corretto-23.0.2x64.msi"; DestDir: "{tmp}"; Flags: ignoreversion deleteafterinstall
; Eclipse JRE
;Source: "E:\cesar\Documents\servidor_impresion\OpenJDK23U-jre_x64_23.0.2.msi"; DestDir: "{tmp}"; Flags: ignoreversion deleteafterinstall
; apache common daemon
;Source: "E:\cesar\Documents\servidor_impresion\prunsrv.exe"; DestDir: "{app}"; Flags: ignoreversion
; la flags onlyifdoesntesist es para que no sobrescriba el archivo si ya existe, ya que ignoreversion sobrescribe los archivos mas viejos por los nuevos
Source: "E:\cesar\Documents\servidor_impresion\printers.properties"; DestDir: "C:\impresorasConfig\"; Flags: onlyifdoesntexist 

; Archivos de Caddy, instalados en una carpeta separada
Source: "E:\cesar\Documents\servidor_impresion\caddy\caddy.exe"; DestDir: "C:\Caddy\"; Flags: onlyifdoesntexist
Source: "E:\cesar\Documents\servidor_impresion\caddy\Caddyfile"; DestDir: "C:\Caddy\"; Flags: onlyifdoesntexist

[CustomMessages]
KeepDataMsg=¿Desea mantener la carpeta de datos de usuario? Si selecciona "No", la carpeta y todos sus contenidos serán eliminados permanentemente.

[Run]
; Instalar Amazon Corretto en modo silencioso
; Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\amazon-corretto-23.0.2x64.msi"""; Description: Instalando JRE; Flags: waituntilidle
;Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\OpenJDK23U-jre_x64_23.0.2.msi"""; Description: Instalando JRE; Flags: waituntilterminated
; Registrar el servicio al finalizar la instalación
;Filename: "{app}\prunsrv.exe"; Parameters: "//IS//PrintServer --Install=""{app}\prunsrv.exe"" --DysplayName=""Servidor de impresion"" --Description=""Servicio de servidor de impresion"" --Startup=auto --Jvm=""{app}\runtime\bin\server\jvm.dll"" --StartMode=exe --StartImage=""{app}\PrintServer.exe"" --StopMode=exe --StopImage=""{app}\PrintServer.exe"" --StopParams=stop --ServiceUser=LocalSystem --StartPath=""{app}\""";
;Filename: "{app}\prunsrv.exe"; Parameters: "//IS//PrintServer --DisplayName=""Servidor de Impresión"" --Description=""Servicion de impresion CDsoft"" --Startup=auto --StartMode=exe --StartImage=""{app}\PrintServer.exe"" --StartPath=""{app}"" --StopMode=exe --StopImage=""{app}\PrintServer.exe"" --StopParams=stop --StopPath=""{app}\PrintServer.exe"" --ServiceUser=LocalSystem --LogPath=""{app}\log"" --LogLevel=Debug --StdOutput=""{app}\log\stdOutput.log"" --StdError=""{app}\log\stdError.log"""; WorkingDir: "{app}"; Flags: runhidden
; correr el servicio
;Filename: "net"; Parameters: "start PrintServer"; Flags: runhidden
; Instalar Caddy como servicio
;Filename: "sc.exe"; Parameters: "create caddy start= auto binPath= ""C:\Caddy\caddy.exe run"""; Flags: runhidden
; Iniciar Caddy como servicio, al iniciar Caddy crea y guarda los certificados CA en C:\Windows\System32\config\systemprofile\AppData\Roaming\Caddy\pki\authorities\local
;Filename: "sc.exe"; Parameters: "start caddy"; Flags: runhidden

; agrgar regla de firewall para el servidor en el puerto 8088
;Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=PrintServer dir=in action=allow protocol=TCP localport=8088"; Flags: runhidden
;Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=PrintServer dir=out action=allow protocol=TCP localport=8088"; Flags: runhidden

[Dirs]
; Asegúrate de que la carpeta de Caddy exista
Name: "C:\Caddy\"; Flags: uninsneveruninstall
Name: "C:\impresorasConfig\"; Flags: uninsneveruninstall

[UninstallRun]
; Detener y eliminar el servicio durante la desinstalación
;Filename: "{app}\prunsrv.exe"; Parameters: "//SS//PrintServer"; Flags: runhidden
;Filename: "{app}\prunsrv.exe"; Parameters: "//DS//PrintServer"; Flags: runhidden
;Filename: "C:\Caddy\caddy.exe"; Parameters: "stop"; Flags: runhidden
;Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=PrintServer"; Flags: runhidden

[Code]
// Define la función para preguntar al usuario durante la desinstalación.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  // Verificamos si estamos en el paso de desinstalación real.
  if CurUninstallStep = usUninstall then
  begin
    // Evitamos mostrar la solicitud en modo silencioso para prevenir cuelgues.
    if not UninstallSilent then
    begin
      // Muestra una caja de mensaje con una pregunta de "Sí/No".
      if MsgBox(ExpandConstant('{cm:KeepDataMsg}'), mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDNO then
      begin
        // Si el usuario elige "No", procede a eliminar la carpeta de datos.
        // DelTree(path, IsDir, DeleteFiles, DeleteSubdirsAlso)
        // El segundo parámetro "True" indica que es un directorio.
        // Los dos últimos "True" indican que elimine archivos y subdirectorios.
        DelTree(ExpandConstant('C:\Caddy'), True, True, True);
        DelTree(ExpandConstant('C:\impresorasConfig'), True, True, True);
      end;
    end;
  end;
end;
